### ISSUE TITLE
log_duplicates_as_sightings = false not working correctly

### ISSUE THREAD

**Issue by koppensb** [CrowdStrike/MISP-tools#101] opened 2023-02-17 06:26 UTC
The setting log_duplicates_as_sightings=false is not working correctly. 
I configured this setting with false but a get sightings  added to MISP.

**Comment by jshcodes** [comment] 2023-04-20 09:10
Caused by a [boolean comparison error](https://github.com/CrowdStrike/MISP-tools/blob/main/cs_misp_import/indicators.py#L595) on the Malware Event indicator check against the `do_sightings` variable.  Resolved by leveraging the [`confirm_boolean_parameter`](https://github.com/CrowdStrike/MISP-tools/blob/main/cs_misp_import/helper.py#L108) helper [when retrieving the value](https://github.com/CrowdStrike/MISP-tools/blob/main/cs_misp_import/indicators.py#L555) from the configuration object.

**Closed** 2023-04-20 11:59 UTC
Labels: bug, current sprint
